Traceback (most recent call last):
  File "/scratch/cube/tuechler/protein_alignment/scripts/SLURM/../align_database.py", line 81, in <module>
    main()
  File "/scratch/cube/tuechler/protein_alignment/scripts/SLURM/../align_database.py", line 71, in main
    shutil.copy(args.input, f"program_out/{name}/data")
  File "/apps/python3/3.9.0/lib/python3.9/shutil.py", line 415, in copy
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/apps/python3/3.9.0/lib/python3.9/shutil.py", line 261, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: '../../data/sp_n10'
0.07user 0.03system 0:00.23elapsed 45%CPU (0avgtext+0avgdata 9140maxresident)k
47inputs+1outputs (0major+2596minor)pagefaults 0swaps
